export const data = [
  {
    no: 1,
    nama: 'Supratmanto',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Harapan Indah',
    kategoriPengajuan: 'Refreshment',
    tanggalPengajuan: '17 Dec 2024 - 14:00',
    lamaBekerja: '2 Tahun',
    alasan: 'Karena anak istrinya harus berpindah ke Jogja',
    status: 'Waiting',
  },
  {
    no: 2,
    nama: 'Bramantyo',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Harapan Indah',
    kategoriPengajuan: 'Refreshment',
    tanggalPengajuan: '17 Dec 2024 - 14:00',
    lamaBekerja: '2 Tahun',
    alasan: 'Karena anak istrinya harus berpindah ke Malang',
    status: 'Done',
  },
  {
    no: 3,
    nama: 'Sulastri',
    lokasi: 'BERIJALAN',
    area: 'DKI 1',
    cabang: 'Cengkareng',
    kategoriPengajuan: 'Additional',
    tanggalPengajuan: '15 Jan 2024 - 09:30',
    lamaBekerja: '5 Tahun',
    alasan: 'Ingin lebih dekat dengan keluarga',
    status: 'Failed',
  },
  {
    no: 4,
    nama: 'Handoko',
    lokasi: 'ACC',
    area: 'Jawa Barat 1',
    cabang: 'Bandung',
    kategoriPengajuan: 'Additional',
    tanggalPengajuan: '03 Feb 2024 - 13:15',
    lamaBekerja: '3 Tahun',
    alasan: 'Alasan kesehatan',
    status: 'Waiting',
  },
  {
    no: 5,
    nama: 'Wulandari',
    lokasi: 'BERIJALAN',
    area: 'Jawa Tengah 2',
    cabang: 'Semarang',
    kategoriPengajuan: 'Refreshment',
    tanggalPengajuan: '28 Mar 2024 - 10:00',
    lamaBekerja: '1 Tahun',
    alasan: 'Merasa jenuh dengan pekerjaan saat ini',
    status: 'Done',
  },
  {
    no: 6,
    nama: 'Prasetyo',
    lokasi: 'ACC',
    area: 'Jawa Timur 1',
    cabang: 'Surabaya',
    kategoriPengajuan: 'Additional',
    tanggalPengajuan: '12 Apr 2024 - 14:45',
    lamaBekerja: '4 Tahun',
    alasan: 'Ingin mengembangkan karir di tempat lain',
    status: 'Failed',
  },
  {
    no: 7,
    nama: 'Yuliana',
    lokasi: 'BERIJALAN',
    area: 'Bali',
    cabang: 'Denpasar',
    kategoriPengajuan: 'Refreshment',
    tanggalPengajuan: '20 Mei 2024 - 11:30',
    lamaBekerja: '2 Tahun',
    alasan: 'Alasan pribadi',
    status: 'Waiting',
  },
  {
    no: 8,
    nama: 'Gunawan',
    lokasi: 'ACC',
    area: 'Sumatera Utara',
    cabang: 'Medan',
    kategoriPengajuan: 'Additional',
    tanggalPengajuan: '05 Jun 2024 - 08:45',
    lamaBekerja: '6 Tahun',
    alasan: 'Ingin kembali ke kampung halaman',
    status: 'Done',
  },
  {
    no: 9,
    nama: 'Rahmawati',
    lokasi: 'BERIJALAN',
    area: 'Kalimantan Selatan',
    cabang: 'Banjarmasin',
    kategoriPengajuan: 'Refreshment',
    tanggalPengajuan: '18 Jul 2024 - 15:20',
    lamaBekerja: '1.5 Tahun',
    alasan: 'Merasa tidak cocok dengan budaya perusahaan',
    status: 'Failed',
  },
  {
    no: 10,
    nama: 'Hermanto',
    lokasi: 'ACC',
    area: 'Sulawesi Selatan',
    cabang: 'Makassar',
    kategoriPengajuan: 'Additional',
    tanggalPengajuan: '30 Aug 2024 - 12:55',
    lamaBekerja: '3.5 Tahun',
    alasan: 'Mendapat tawaran pekerjaan yang lebih baik',
    status: 'Waiting',
  },
]
