export const data = {
  roles: [
    {
      no: 1,
      roleName: 'Super Admin',
      description: 'Akses untuk semua menu dan fitur',
      createdDate: '12/05/2024',
      status: 'Y',
    },
    {
      no: 2,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'Y',
    },
    {
      no: 3,
      roleName: 'Cabang FAT',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
    {
      no: 4,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
    {
      no: 5,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
    {
      no: 6,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
    {
      no: 7,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
    {
      no: 8,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
    {
      no: 9,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
    {
      no: 10,
      roleName: 'Admin',
      description: 'bikomaryono@gmail.com',
      createdDate: '12/05/2024',
      status: 'N',
    },
  ],
  pagination: {
    current_page: 1,
    total_pages: 12,
    total_roles: 120,
    roles_per_page: 10,
  },
}
