export const data = [
  {
    no: 1,
    submissionDate: '10:00 - 10 Feb 2024',
    name: 'Supratmanto',
    location: 'ACC',
    vehicleType: 'Operational Khusus',
    driver: 'Ya',
    policeNumber: 'Ganjil',
    bookingDate: '24 Dec - 26 Dec 2024',
    bookingTime: '18.00 - 21.00',
    requestCapacity: '6 Orang',
    reason: 'Acara Ramadhan',
    bastForm: '-',
    status: 'Waiting',
    detail: {
      location: 'ACC',
      detailUnit: 'Toyota Innova Reborn 2022',
      capacity: '1',
      transmission: 'Manual',
      platNumber: 'B 1233 - Ganjil',
      fuel: 'Bensin',
    },
  },
  {
    no: 2,
    submissionDate: '10:00 - 10 Feb 2024',
    name: 'Supratmanto',
    location: 'BERIJALAN',
    bookingDate: '24 Dec - 26 Dec 2024',
    bookingTime: '18.00 - 21.00',
    requestCapacity: '6 Orang',
    facility: 'proyektor, meja, kursi',
    reason: 'Acara Ramadhan',
    description:
      'Mohon untuk bangku disediakan sebanyak 30 kursi dengan letter L. Untuk teman-teman yang nanti datang.',
    submittedLayout: '-',
    status: 'Waiting',
    detail: {
      location: 'ACC',
      titleRoom: '201',
      floor: '1',
      description: 'lorem ipsum dolor sit amet',
      terms: 'lorem ipsum dolor sit amet',
      facility: 'lorem ipsum dolor sit amet',
    },
  },
  {
    no: 3,
    submissionDate: '10:00 - 10 Feb 2024',
    manpowerCategory: 'Additional',
    name: 'Supratmanto',
    gender: 'Laki-laki',
    location: 'BERIJALAN',
    bookingDate: '24 Dec - 26 Dec 2024',
    bookingTime: '18.00 - 21.00',
    reason: 'Acara Ramadhan',
    manpowerNeeds: '6 Orang',
    status: 'Waiting',
    detail: {
      manpowerNeeds: '6 Orang',
    },
  },
]
