export const data = [
  {
    pathImage: ['path://', 'path://'],
    titleRoom: '203',
    lokasi: 'ACC',
    lantaiRuangan: 'Lantai 3',
    kapasitas: '3 Orang',
    status: 'Active',
  },
  {
    pathImage: ['path://', 'path://'],
    titleRoom: '206',
    lokasi: 'BERIJALAN',
    lantaiRuangan: 'Lantai 1',
    kapasitas: '4 Orang',
    status: 'Non-Active',
  },
  {
    pathImage: ['path://', 'path://'],
    titleRoom: '204',
    lokasi: 'ACC',
    lantaiRuangan: 'Lantai 4',
    kapasitas: '4 Orang',
    status: 'Active',
  },
  {
    pathImage: ['path://', 'path://'],
    titleRoom: '205',
    lokasi: 'BERIJALAN',
    lantaiRuangan: 'Lantai 1',
    kapasitas: '6 Orang',
    status: 'Active',
  },
  {
    pathImage: ['/document/master-room/room-image/7cedbf4e-b855-4e2a-b4e5-8ee9cd94e9db_Capture.PNG'],
    titleRoom: '230',
    lokasi: 'ACC',
    lantaiRuangan: 'Lantai 2',
    kapasitas: '6 Orang',
    status: 'Active',
  },
  {
    pathImage: ['/document/master-room/room-image/39e3da56-7382-455b-b745-411fb758ca15_Capture.PNG'],
    titleRoom: '229',
    lokasi: 'ACC',
    lantaiRuangan: 'Lantai 20',
    kapasitas: '6 Orang',
    status: 'Active',
  },
  {
    pathImage: ['/document/master-room/room-image/9f16fce7-a7d0-45e2-99e8-51c9113a555f_large-image.png'],
    titleRoom: '226',
    lokasi: 'ACC',
    lantaiRuangan: 'Lantai 20',
    kapasitas: '6 Orang',
    status: 'Active',
  },
  {
    pathImage: ['/document/master-room/room-image/ac884243-bb49-4bf3-93ba-ba0c7fdaeb21_Capture.PNG'],
    titleRoom: '229',
    lokasi: 'ACC',
    lantaiRuangan: 'Lantai 20',
    kapasitas: '6 Orang',
    status: 'Active',
  },
  {
    pathImage: [
      'https://d2mo2a5fvrklap.cloudfront.net/app/uploads/sites/7/2022/08/12164213/scdbjakarta-staylist-1kingbedstudio-landscape.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-J7cONVqmTWKHaaFkpDqMCwtICUzVSZGP9g&s',
    ],
    titleRoom: '101',
    lokasi: 'ACC',
    lantaiRuangan: 'Lantai 1',
    kapasitas: '6 Orang',
    status: 'Active',
  },
  {
    pathImage: ['path://', 'path://'],
    titleRoom: '207',
    lokasi: 'BERIJALAN',
    lantaiRuangan: 'Lantai 2',
    kapasitas: '8 Orang',
    status: 'Active',
  },
  {
    pathImage: ['path://', 'path://'],
    titleRoom: '208',
    lokasi: 'BERIJALAN',
    lantaiRuangan: 'Lantai 2',
    kapasitas: '10 Orang',
    status: 'Active',
  },
  {
    pathImage: ['path://', 'path://'],
    titleRoom: '201',
    lokasi: 'BERIJALAN',
    lantaiRuangan: 'Lantai 3',
    kapasitas: '10 Orang',
    status: 'Non-Active',
  },
]
