export const data = {
  users: [
    {
      no: 1,
      idUser: 'FAT.zokaj',
      name: 'Vgmjmipsob Sotsljym',
      email: 'uurssugs@vvsbg.com',
      noHP: '0383960453144',
      role: '-',
      status: 'N',
    },
    {
      no: 2,
      idUser: 'FAT.djphi',
      name: 'Uzoowrlbtv Fvebiuha',
      email: 'nvyoevyo@qnkff.com',
      noHP: '0152168938693',
      role: 'CRSH',
      status: 'R',
    },
    {
      no: 3,
      idUser: 'FAT.bixdo',
      name: 'Ltslykirqp Evdgglsh',
      email: 'wexdurmb@ecmoo.com',
      noHP: '0870599358871',
      status: 'N',
      role: '-',
    },
    {
      no: 4,
      idUser: 'FAT.isyew',
      name: 'Iympjoqslr Sjmjqvix',
      email: 'zjhhffea@nyaxv.com',
      noHP: '0840679494089',
      status: 'N',
      role: '-',
    },
    {
      no: 5,
      idUser: 'FAT.tycnh',
      name: 'Qqzpkopfkb Qxvdhzyb',
      email: 'foiqgjjr@qgvrz.com',
      noHP: '0792492584706',
      status: 'R',
      role: 'RRBOH',
    },
    {
      no: 6,
      idUser: 'FAT.iczbd',
      name: 'Zcsvfgontf Ruglapux',
      email: 'ecqgroto@tuajs.com',
      noHP: '0159328425554',
      status: 'N',
      role: '-',
    },
    {
      no: 7,
      idUser: 'FAT.ldcoc',
      name: 'Yysngpvfmd Llcrvuwm',
      email: 'gslwqyhp@ufoxi.com',
      noHP: '0494654378843',
      status: 'R',
      role: 'RODH',
    },
    {
      no: 8,
      idUser: 'FAT.mczvi',
      name: 'Zsibahyqek Afdmkuxg',
      email: 'sknzivfq@rjhkg.com',
      noHP: '0829174268687',
      status: 'N',
      role: '-',
    },
    {
      no: 9,
      idUser: 'FAT.ihutu',
      name: 'Qbrbmecljq Ocptprfj',
      email: 'xfeeluae@pxrpp.com',
      noHP: '0328078682418',
      status: 'R',
      role: 'SUAH',
    },
    {
      no: 10,
      idUser: 'FAT.qcvqg',
      name: 'Xqpqajuead Bluwcrnk',
      email: 'aoflffts@yykyj.com',
      noHP: '0664424920031',
      status: 'R',
      role: 'CRSH',
    },
  ],
  pagination: {
    current_page: 1,
    total_pages: 24,
    total_users: 120,
    users_per_page: 10,
  },
}
