export const data = {
  no: 1,
  name: 'BIKO MARYONO',
  location: 'ACC',
  vehicleType: 'Operational Khusus',
  withDriver: 'Ya',
  ganjilGenap: 'Ganjil',
  capacity: '6 Orang',
  reason: 'lorem ipsum dolor sit amet',
  dtUpload: '10 Feb 2024 - 10:00',
  bookingDate: '18/10/2024 - 20/11/2024',
  bookingTime: '10:00 - 13:00',
  status: 'Selesai',
  detailUnit: 'Toyota Innova Reborn 2022',
  transmision: 'Manual',
  plateNumber: 'B1234ACC - GANJIL',
  fuelType: 'Bensin',
  description: 'lorem ipsum dolor sit amet',
  facility: 'lorem ipsum dolor sit amet',
}
