export const data = [
  {
    no: 1,
    nama: 'Jack',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Harapan Indah',
    kwhMeterExisting: '100 KG',
    kwhMeterRequest: '150 KG',
    tanggalPengajuan: '17 Dec 2024 - 14:00',
    status: 'Waiting',
  },
  {
    no: 2,
    nama: 'Bob',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Harapan Indah',
    kwhMeterExisting: '100 KG',
    kwhMeterRequest: '150 KG',
    tanggalPengajuan: '17 Dec 2024 - 14:00',
    status: 'Done',
  },
  {
    no: 3,
    nama: 'Eve',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Harapan Indah',
    kwhMeterExisting: '100 KG',
    kwhMeterRequest: '150 KG',
    tanggalPengajuan: '17 Dec 2024 - 14:00',
    status: 'Failed',
  },
  {
    no: 4,
    nama: 'Eve',
    lokasi: 'ACC',
    area: 'Jawa Barat 1',
    cabang: 'Cempaka Putih',
    kwhMeterExisting: '223 KG',
    kwhMeterRequest: '225 KG',
    tanggalPengajuan: '21 Aug 2023 - 10:09',
    status: 'Waiting',
  },
  {
    no: 5,
    nama: 'Jack',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Harapan Indah',
    kwhMeterExisting: '219 KG',
    kwhMeterRequest: '163 KG',
    tanggalPengajuan: '26 Dec 2024 - 05:19',
    status: 'Waiting',
  },
  {
    no: 6,
    nama: 'Helen',
    lokasi: 'Jakarta',
    area: 'DKI 1',
    cabang: 'Cempaka Putih',
    kwhMeterExisting: '186 KG',
    kwhMeterRequest: '129 KG',
    tanggalPengajuan: '14 Nov 2024 - 01:06',
    status: 'Waiting',
  },
  {
    no: 7,
    nama: 'Frank',
    lokasi: 'Jakarta',
    area: 'DKI 1',
    cabang: 'Cempaka Putih',
    kwhMeterExisting: '153 KG',
    kwhMeterRequest: '211 KG',
    tanggalPengajuan: '19 Jun 2024 - 12:10',
    status: 'Waiting',
  },
  {
    no: 8,
    nama: 'Alice',
    lokasi: 'Jakarta',
    area: 'DKI 1',
    cabang: 'Harapan Indah',
    kwhMeterExisting: '296 KG',
    kwhMeterRequest: '246 KG',
    tanggalPengajuan: '10 Jan 2023 - 10:59',
    status: 'Waiting',
  },
  {
    no: 9,
    nama: 'Charlie',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Harapan Indah',
    kwhMeterExisting: '263 KG',
    kwhMeterRequest: '270 KG',
    tanggalPengajuan: '19 Feb 2023 - 07:37',
    status: 'Failed',
  },
  {
    no: 10,
    nama: 'Frank',
    lokasi: 'ACC',
    area: 'DKI 2',
    cabang: 'Dago',
    kwhMeterExisting: '283 KG',
    kwhMeterRequest: '79 KG',
    tanggalPengajuan: '12 Sep 2024 - 12:04',
    status: 'Waiting',
  },
]
