export const data = {
  users: [
    {
      no: 1,
      name: 'Biko Maryono',
      npk: '18012',
      email: 'bikomaryono@gmail.com',
      role: 'Super Admin',
      status: 'Y',
    },
    {
      no: 2,
      name: 'Biko Maryono',
      npk: '18012',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'Y',
    },
    {
      no: 3,
      name: 'Biko Maryono',
      npk: '18012',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
    {
      no: 4,
      name: 'Biko Maryono',
      npk: '18012',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
    {
      no: 5,
      name: 'Biko Maryono',
      npk: '-',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
    {
      no: 6,
      name: 'Biko Maryono',
      npk: '-',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
    {
      no: 7,
      name: 'Biko Maryono',
      npk: 'Biko Maryono',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
    {
      no: 8,
      name: 'Biko Maryono',
      npk: 'Biko Maryono',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
    {
      no: 9,
      name: 'Biko Maryono',
      npk: 'Biko Maryono',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
    {
      no: 10,
      name: 'Biko Maryono',
      npk: 'Biko Maryono',
      email: 'bikomaryono@gmail.com',
      role: 'Admin',
      status: 'N',
    },
  ],
  pagination: {
    current_page: 1,
    total_pages: 24,
    total_users: 120,
    users_per_page: 10,
  },
}
