export const data = {
  no: 1,
  name: 'BIKO MARYONO',
  location: 'ACC',
  roomTitle: '201',
  roomFloor: 'Lantai 2',
  roomCapacity: '6 Orang',
  reason: 'lorem ipsum dolor sit amet',
  dtUpload: '10 Feb 2024 - 10:00',
  bookingDate: '18/10/2024 - 20/11/2024',
  bookingTime: '10:00 - 13:00',
  status: 'Selesai',
  description: 'lorem ipsum dolor sit amet',
  descriptionRoom: 'lorem ipsum dolor sit amet',
  termConditions: 'lorem ipsum dolor sit amet',
  facility: 'lorem ipsum dolor sit amet',
  facilityRoom: 'lorem ipsum dolor sit amet',
}
