export const data = {
  users: [
    {
      no: 1,
      idUser: 'FAT.zokaj',
      name: 'Vgmjmipsob Sotsljym',
      email: 'uurssugs@vvsbg.com',
      noHP: '0383960453144',
      role: 'CRSH',
      status: 'N',
    },
    {
      no: 2,
      idUser: 'FAT.djphi',
      name: 'Uzoowrlbtv Fvebiuha',
      email: 'nvyoevyo@qnkff.com',
      noHP: '0152168938693',
      role: 'BM',
      status: 'Y',
    },
    {
      no: 3,
      idUser: 'FAT.zsreb',
      name: 'Ayozdcywxk Uaygbfsx',
      email: 'kjvksmqt@mnwwc.com',
      noHP: '0977356682435',
      role: 'CRSH',
      status: 'Y',
    },
    {
      no: 4,
      idUser: 'FAT.gtcbp',
      name: 'Rcjwhrhlzz Iyviwdtj',
      email: 'hhwxsymv@mqwah.com',
      noHP: '0892130616351',
      role: 'CRSH',
      status: 'N',
    },
    {
      no: 5,
      idUser: 'FAT.uwnbj',
      name: 'Guozawdetr Tpnbcffe',
      email: 'ljwddbhw@iivbg.com',
      noHP: '0457113421960',
      role: 'RROBH',
      status: 'Y',
    },
    {
      no: 6,
      idUser: 'FAT.idknw',
      name: 'Bujqtaffyp Bdhyifiy',
      email: 'kgvdvtat@jvmao.com',
      noHP: '0346197489829',
      role: 'RODH',
      status: 'Y',
    },
    {
      no: 7,
      idUser: 'FAT.rumlh',
      name: 'Vjoyxiwnvb Qfnoeojk',
      email: 'rgpkuvlb@vhzix.com',
      noHP: '0245827373083',
      role: 'RROBH',
      status: 'Y',
    },
    {
      no: 8,
      idUser: 'FAT.tjeec',
      name: 'Zmnoivoghp Xixkhwsk',
      email: 'lfrezjhv@cnpai.com',
      noHP: '0683113410641',
      role: 'Cabang',
      status: 'N',
    },
    {
      no: 9,
      idUser: 'FAT.avrna',
      name: 'Mngrwdwmhv Kpqcfbmu',
      email: 'sexccwbn@jezis.com',
      noHP: '0151700488684',
      role: 'RROBH',
      status: 'N',
    },
    {
      no: 10,
      idUser: 'FAT.vhqgh',
      name: 'Vrxlxuzpbq Aynbtswn',
      email: 'kiyqyvep@sbplw.com',
      noHP: '0423106473002',
      role: 'Cabang',
      status: 'N',
    },
  ],
  pagination: {
    current_page: 1,
    total_pages: 24,
    total_users: 120,
    users_per_page: 10,
  },
}
